### ISSUE TITLE
Including a space after "templateUrl" causes the router to throw "Failed to load <template>"

### ISSUE THREAD

**Issue by sky-coding** [TheLarkInn/angular2-template-loader#10]
Including a space after `templateUrl`, e.g. `templateUrl : './home.template.html'` instead of `templateUrl: './home.template.html'` causes the router to throw `Failed to load about.template.html` at runtime.

Obviously this can be worked around, but a coworker who prefers spaces after his properties was about ready to flip his keyboard today when trying to load a template, and this could be a gotcha for other developers unaware of this restriction.

https://github.com/AngularClass/angular2-webpack-starter/issues/733#issuecomment-228936231

**Comment by TheLarkInn** [comment]
Nice catch. I'll take a PR, only cause I'm swamped I can look Into this in a few days.

**Comment by TheLarkInn** [comment]
Ohhhhhhh regex...

**Comment by sky-coding** [comment]
Done, thanks for creating and maintaining this loader!
