### ISSUE TITLE
Styles to string conversion

### ISSUE THREAD

**Issue by petoknm** [TheLarkInn/angular2-template-loader#14]
Hi
I am using this loader to load styles to my application and it really sucks that I need to change my webpack config for css files from "css" to "to-string!css" because I need to use styles elsewhere in my app and I don't want them to be strings. Basically I am stuck with only "css" loader for my app to work. My question is shouldn't this loader convert css into strings internally? Because its only job is to take css(and html) and load it as a string to the component.

**Comment by TheLarkInn** [comment]
Did you try using `raw-loader` instead as the ending of your loader chain?
