### ISSUE TITLE
Sourcemap does not show original source

### ISSUE THREAD

**Issue by wesleymooiman** [TheLarkInn/angular2-template-loader#17]
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
Given the following webpack configuration:

```typescript
exports.typescriptModule = function() {
  return {
    test: /\.ts$/,
    loaders: ['ts', 'angular2-template-loader']
  }
};
```

```typescript
{
  test: /\.scss$/,
  include: helpers.root('src'),
  loaders: ['raw', 'sass']
}
```  

And this component:
```typescript
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';
import '../../public/css/styles.scss';

@Component({
  selector: 'my-app',
  templateUrl: './app.html',
  styleUrls: ['./app.scss'],
  directives: [ROUTER_DIRECTIVES]
})
export class AppComponent { }
```

Note that templateUrl and styleUrls is used.

When sourcemaps are created it shows the following sourcemap:
```typescript
import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';
import '../../public/css/styles.scss';

@Component({
  selector: 'my-app',
  template: require('./app.html'),
  styles: [require('./app.scss')],
  directives: [ROUTER_DIRECTIVES]
})
export class AppComponent { }


/** WEBPACK FOOTER **
 ** ./~/angular2-template-loader!./src/app/app.ts
 **/
```

Note the sourcemap shows template and styles with their require calls, instead of the original source.

**Expected/desired behavior**
Sourcemap should contain the original typescript code.

* **angular2-template-loader version:** 0.4.0

**Comment by TheLarkInn** [comment]
In the latest branch that I am working on, I'm going to be removing those requires, so that instead the templates themself will resolve inline, after going through the loader chain. So hopefully this should fix this problem.

**Comment by TheLarkInn** [comment]
Tying to https://github.com/TheLarkInn/angular2-template-loader/issues/18
