### ISSUE TITLE
Works perfectly with ts-loader!

### ISSUE THREAD

**Issue by cebor** [TheLarkInn/angular2-template-loader#2]
Just testet it with the offical ts-loader and it works perfectly, cause ts-loader has the text-pipe activated by default!

Please mention this, in your README ...

BTW: Great Work :)

**Comment by cebor** [comment]
See: https://github.com/cebor/ng2-start/blob/master/config/webpack.common.js#L35

**Comment by TheLarkInn** [comment]
@cebor this is actually great news!! I tried implementing it and was having issues, I'll look at your example!! Also PR's welcome :smirk:

**Comment by cebor** [comment]
No PR needed, just use it :)

**Comment by TheLarkInn** [comment]
No I mean PR to update the readme. 😎

**Comment by TheLarkInn** [comment]
Fixed with d27cfe7d7d77750f9cca0d7e399ff58140f69ad1 (hopefully this will suffice @cebor ) if you want something more comprehensive, feel free to submit a PR. 🙏

**Comment by gdi2290** [comment]
I'm having problems with this and ts-loader
https://github.com/angular/universal-starter/tree/angular2-template-loader
<img width="1095" alt="screen shot 2016-06-21 at 11 52 18 am" src="https://cloud.githubusercontent.com/assets/1016365/16242284/a1fabce0-37a6-11e6-8448-c27ee7cb9e1a.png">

**Comment by cebor** [comment]
@gdi2290 have you added a raw-loader for `.html` and `.css` files ?

**Comment by gdi2290** [comment]
yup that was it thanks

**Comment by TheLarkInn** [comment]
Do you think specifying raw-loader as a peer dependency will help people not miss that catch?  I don't want to use it from within the loader because it limits the chaining potential.

**Comment by gdi2290** [comment]
mentioning that you need loaders for html and css is all that's needed
