### ISSUE TITLE
There should be an error displayed in console when tsconfig is missing the awesomeTypescriptLoaderOptions

### ISSUE THREAD

**Issue by etiennejcharles** [TheLarkInn/angular2-template-loader#25]
By the way, amazing job on that plugin! Thanks for the help it brings to the typescript devs out there!

In order to make sure my unit tests in typescript and Angular2 work, I had to add this snippet to my tsconfig.js

```
"awesomeTypescriptLoaderOptions": {
        "useWebpackText": true
        // Allows other loaders to be chained to awesome-typescript-loader.
    },
```

Shouldn't there be some sort of warning mentionning that it's required when you use it wih the awesome-typescript-loader ? Probably lost 4/5 hours trying to fetch that.

Let me know what you think
E

**Comment by TheLarkInn** [comment]
I think it's a great idea, however I personally don't have time to implement something like this. Would accept a PR.

**Comment by etiennejcharles** [comment]
It's been 4 years, and I mostly been using React - If anyone wants to be pick it up, feel free!
