### ISSUE TITLE
docs(readme): ts-loader mentioned instead of awesome-typescript-loader

### ISSUE THREAD

**Issue by BrainCrumbz** [TheLarkInn/angular2-template-loader#26]
In **Example Markup** section, text says _"Here is an example markup of the webpack.config.js, which chains the angular2-template-loader to the **tsloader**"_, but then following code block only uses **angular2-template-loader**. 
HTH

**Comment by BrainCrumbz** [comment]
Or, looking at subsequent section (**Awesome Typescript Loader**) maybe is the other way around: the text is right, and code block should use **ts-loader** instead.

**Comment by TheLarkInn** [comment]
Would happily accept a PR!!!

**Comment by BrainCrumbz** [comment]
happy with that. Which is the right one: code block or text?

**Comment by vivekmore** [comment]
Yes - which is the right one?
I believe the code block needs to be corrected/changed to say **ts**
