### ISSUE TITLE
chore(build): isn't `codecov` a development-only dependency?

### ISSUE THREAD

**Issue by BrainCrumbz** [TheLarkInn/angular2-template-loader#27]
Just installed loader in one of our team project, and noticed *codecov@1.0.1* as a sub-dependency. Just wondering if installed package can be slimmed down.
Thanks.

**Comment by hyp3rdino** [comment]
Size is just one issue: _codecov_ as general dependency causes _npm install_ to fail on _NodeJS >=0.12.x_. _codecov@1.0.1_ apparently requires an incompatible and no longer maintained sub-dependency _execSync_.
├─ codecov@1.0.1
│  ├─ execSync@1.0.2

See:
[execSync: Troubles with Node 0.12 #38](https://github.com/mgutz/execSync/issues/38)

**Comment by tdsmithATabc** [comment]
Yeah `execSync` fails with a `Native code compile failed!` for my team. It also relies on `graceful-fs@1.2.3` which throws up a number of compatibility warnings. (The current version is something like 4.1.8, which is what most of my other deps use.)

I know defeating npm dependency warnings is often an impossible goal, but this is the only one stopping me right now. 😛

**Comment by hyp3rdino** [comment]
I forked this project and moved ```codecov``` dependency to ```devDependencies``` which solves the ```Native code compile failed!``` issue for me. Anyhow, the issue looks only scary but the installation works fine regardless: effectively ```codecov``` is NOT used by any production code and  ```npm install``` downloads all the really needed dependencies properly . This issue is primarily misleading and bloats the package.

**Comment by halfzebra** [comment]
@hyp3rdino can you send a PR?

**Comment by halfzebra** [comment]
I went ahead and created a PR #33
