### ISSUE TITLE
Failed to load component CSS during test with karma & webpack

### ISSUE THREAD

**Issue by GiuseppePiscopo** [TheLarkInn/angular2-template-loader#28]
Hi there

I tried, by searching around, if there was already a similar issue/thread/question, but it seems not. I also checked for similar spec files in angular2-webpack-starter, but strangely enough none of those was showing the present use case, so maybe it's something known and someone is already working at it. Here's the issue:

a simple AppComponent like those found in quickstart or tour of heroes has an inline `template` and then style is pointed to like `styleUrls: ['./app.component.css'],`. When running a smoke test spec, as soon as we try to configure testing module with component as a *declaration*, test fails because it fails to load CSS file (full stacktrace is appended below, at the end):

```
Failed: Uncaught (in promise): Failed to load app.component.css
resolvePromise@webpack:////path/to/proj/~/zone.js/dist/zone.js:418:0 <- /path/to/proj/src/client/karma-entry.js:11799:76
```

If instead style is manually `require`d as in `styles: [require('./app.component.css')],` the error goes away. This led me here on angular2-template-loader to ask whether it's a known issue or more likely there's something wrong with our setup. 

Environment details and code samples follow: 

* angular 2: 2.0.0 final
* webpack: 1.13.2
* angular2-template-loader: 0.5.0
* karma: 1.3.0

```ts
// src/client/app/app.component.ts

@Component({
  selector: 'my-app',
  template: `
    <h1>{{title}}</h1>
    <nav>
      <a routerLink="/dashboard">Dashboard</a>
      <a routerLink="/heroes">Heroes</a>
    </nav>
    <router-outlet></router-outlet>
  `,
  styleUrls: ['./app.component.css'],  // this fails
  //styles: [require('./app.component.css')],  // this does not fail
})
export class AppComponent {
  title = 'Tour of Heroes';
}
```

```ts
// src/client/app/app.component-decl.spec.ts

describe('AppComponent as declaration', () => {
  beforeEach(async(() => {
    // refine the test module by declaring the test component
    TestBed.configureTestingModule({
      declarations: [ AppComponent ],
    });
    TestBed.compileComponents();
  }));

  it('should complete beforeEach', () => expect(true).toBe(true));
});
```

Besides, as a reference:

* sample GitHub project is reachable [here](https://github.com/BrainCrumbz/YANGTSE)
* App component is [here](https://github.com/BrainCrumbz/YANGTSE/blob/master/src/client/app/app.component.ts), 
* App component spec file is [here](https://github.com/BrainCrumbz/YANGTSE/blob/master/src/client/app/app.component-decl.spec.ts)

Test output full stacktrace:

```
Failed: Uncaught (in promise): Failed to load app.component.css
resolvePromise@webpack:////path/to/proj/~/zone.js/dist/zone.js:418:0 <- /path/to/proj/src/client/karma-entry.js:11799:76
resolvePromise@webpack:////path/to/proj/~/zone.js/dist/zone.js:403:0 <- /path/to/proj/src/client/karma-entry.js:11784:32
webpack:////path/to/proj/~/zone.js/dist/zone.js:451:0 <- /path/to/proj/src/client/karma-entry.js:11832:32
invokeTask@webpack:////path/to/proj/~/zone.js/dist/zone.js:225:0 <- /path/to/proj/src/client/karma-entry.js:11606:43
onInvokeTask@webpack:////path/to/proj/~/zone.js/dist/proxy.js:84:0 <- /path/to/proj/src/client/karma-entry.js:13267:54
invokeTask@webpack:////path/to/proj/~/zone.js/dist/zone.js:224:0 <- /path/to/proj/src/client/karma-entry.js:11605:55
runTask@webpack:////path/to/proj/~/zone.js/dist/zone.js:125:0 <- /path/to/proj/src/client/karma-entry.js:11506:58
drainMicroTaskQueue@webpack:////path/to/proj/~/zone.js/dist/zone.js:357:0 <- /path/to/proj/src/client/karma-entry.js:11738:43
run@webpack:////path/to/proj/~/core-js/modules/es6.promise.js:87:0 <- /path/to/proj/src/client/karma-entry.js:4074:30
webpack:////path/to/proj/~/core-js/modules/es6.promise.js:100:0 <- /path/to/proj/src/client/karma-entry.js:4087:32
flush@webpack:////path/to/proj/~/core-js/modules/_microtask.js:18:0 <- /path/to/proj/src/client/karma-entry.js:4442:12
```

**EDIT**
Further detail: all is fine at build-time and runtime for development build (e.g. not in test, but just running web app locally). One difference between development and test configurations is that webpack *cache* is enabled in development build, disabled in test.

**Comment by GiuseppePiscopo** [comment]
Ok. Found problem, on my side. Adding some console logging to own angular2-template-loader `index.js` showed that loader was not invoked when running tests, and of course was invoked when building in development.

It turned out that, in webpack configuration, angular2-template-loader was only applied to non-spec source files, while spec files only got awesome-typescript-loader. So I guess that when spec source was importing a component, its corresponding source was not going through angular2-template-loader as well. Which is a different behaviour than what I thought.

**Comment by jonbonraki** [comment]
can you share your configuration for angular2-template-loader. i m also facing the same issue.

**Comment by GiuseppePiscopo** [comment]
@jonbonraki hi there. Sorry that project in the meantime has moved on since, then I've not been touching that for quite some time. Here's the bit of info you might be interested in: 

* [project](https://github.com/BrainCrumbz/YANGTSE)
* [webpack test config file](https://github.com/BrainCrumbz/YANGTSE/blob/dbfc6861b6c1618812e7c1566913bb68c36e0c88/webpack.config.test.js): it basically picks selected chunks of configuration from a common config file
* [webpack common config file](https://github.com/BrainCrumbz/YANGTSE/blob/dbfc6861b6c1618812e7c1566913bb68c36e0c88/webpack.common.js): the interesting bit should be `typescriptTest` rule, 

It seems to me that CSS problem is gone, although one of the tests fails for other reasons.
