### ISSUE TITLE
include styles that live in node_modules

### ISSUE THREAD

**Issue by tomgeorge** [TheLarkInn/angular2-template-loader#31]
Hi,

if I try to do something like 

```
styleUrls: [
     './index.css',
    'materialize-css/dist/css/materialize.css'
]
```

it gets turned into:

```
styles: [
    require('./index.css'),
    require('./materialize-css/dist/css/materialize.css'
]
```

I could just use a relative path, or `import 'materialize-css/dist/css/materialize.css` but I'd rather use the styleUrls option if I could.  Do you know how I could accomplish this?

**Comment by TheLarkInn** [comment]
This one is kind of tough to tackle. The intentional design of the loader was to let angular2 users write 'idiomatic' angular components IE specify non strict relative pathing. Which with SystemJS etc. You would not specify the ./

A workaround I suppose would be to provide the true relative path to the node module which I know is not ideal. 

If you have some suggestions for this or a preference for the loader I would consider a PR.

**Comment by tomgeorge** [comment]
I made a little hack to your loader where if I preface a style with `~`, kind of like how you would import a sass file in sass, it resolves to node_modules.  So it ends up looking like 

```typescript
styleUrls: [
     './index.css',
    '~materialize-css/dist/css/materialize.css'
]
```

Is that something you'd be interested in?  I could do a PR for that.

**Comment by TheLarkInn** [comment]
I would allow it but not as default functionality. So using loaderUtils.parseQuery you can get the options object passed from the loader definition. Let's have a property that will be a boolean turning on or off for this functionality. Sound good?

**Comment by TheLarkInn** [comment]
And part of the pr will need to be an update to the readme and tests.

**Comment by tomgeorge** [comment]
Sounds good. I'll take a whack at it.

**Comment by tomgeorge** [comment]
I'm having a hard time thinking of a good name  for the flag.  I think something like

`resolveNodeModules: true`

or

`nodeModuleResolution: true`

Do you have any preference/suggestion?

Does this need to work for webpack1 and webpack2?

Thanks

**Comment by TheLarkInn** [comment]
Being a webpack maintainer myself im biased and would say we want it to work just for webpack 2, however I believe that by using webpack/loader-utils @ latest, the api for .parseQuery should support both the query and options object properties.

**Comment by intellix** [comment]
We're attempting to load templates that come from a node_module for being able to override and include templates from another project of ours.

We wanna do something like:

```ts
// Inside C3PO - Use templateUrl relative to this project
templateUrl: './footer/footer.html'
```
or 
```ts
/// C3PO depends on R2D2 so let's use theirs:
templateUrl: 'node_modules/r2d2/app/footer/footer.html'
```

It seems to me that it shouldn't be restrictive in anyway. Why only limit to relative with `./`?

**Comment by VictorLeach96** [comment]
My solution for this is to import them at a global level and use the following loader.

```
{ 
	test: /\.css$/, 
	use: ExtractTextPlugin.extract('css-loader'),
	exclude: /(\.async\.css$|src)/
}
```

**Comment by maverikarsh** [comment]
You can declare styles in node_modules inside .angular-cli.json files

**Comment by maxfahl** [comment]
Is it possible to resolve absolute paths yet? i've tried adding the following to my webpack config using 0.6.2 without any luck:

```typescript
{
  loader: 'angular2-template-loader',
  options: {
    useAbsoluteUrls: true
}
```

**Comment by maxfahl** [comment]
I see now that the option is not yet available in 0.6.2. Is this planned on getting added soon?

**Comment by elsasslegend** [comment]
Can it be added soon please ? We still have this problem since one year, we had to fork this lib until now.

**Comment by intellix** [comment]
In regards to this comment by @TheLarkInn about why it's not being done: 

> The intentional design of the loader was to let angular2 users write 'idiomatic' angular components IE specify non strict relative pathing. Which with SystemJS etc. You would not specify the ./

I'd say this might be irrelevant now, as CLI has defaulted and expected users to write the ./ manually for a long time now: https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts#L10

Removing this logic would allow us to do much more in Angular CLI (like for example depending on templates that provide Bootstrap and another project depending on Material ones). 

The lack of flexibility when using Angular/Angular CLI is the biggest reason I regret choosing it. People are suffering trying to create things a little more ambitious than the creators envisioned and they just won't budge.

If we ever get this, I will eat my shoe in celebration

**Comment by intellix** [comment]
Related: https://github.com/angular/angular-cli/issues/9766

**Comment by tomgeorge** [comment]
Hi, I'm sorry that I have not looked at this in a while.  I no longer am writing angular2 applications professionally, and with the advent of angular-cli, this sort of webpack tweaking is sort of hidden from you, now.  I'm closing this issue, and again I apologize for the lack of movement on it.
