### ISSUE TITLE
Don't chain with awesome-typescript-loader

### ISSUE THREAD

**Issue by ghetolay** [TheLarkInn/angular2-template-loader#34]
Hi,

I'm having trouble making it work with awesome-typescript-loader.
I'm currently using the latest versions of all modules as follow : 

```json
"devDependencies": {
    "angular2-template-loader": "^0.5.0",
    "awesome-typescript-loader": "^2.2.4",
    "typescript": "^2.0.3",
    "webpack": "^2.1.0-beta.25"
}
```

But I tried some others versions combinations and still couldn't make it work.

It works with `ts-loader` or if you set the component as the main entry on webpack (totally useless but might help to find out what's going on). 

I've created a minimal [project to demonstrate](https://github.com/ghetolay/Test_angular_loaders), if you need more information about source code or tsconfig you can check it directly on the repo.

**Comment by nikolasleblanc** [comment]
@ghetolay angular2-template-loader and awesome-typescript-loader do not work together if `declaration: true` is set in your tsconfig.json, which, judging by your sample app, is the case: https://github.com/ghetolay/Test_angular_loaders/blob/master/tsconfig.json#L3.

See https://github.com/TheLarkInn/angular2-template-loader/issues/19

**Comment by nikolasleblanc** [comment]
The good news is, `ts-loader` works fine angular2-template-loader with declaration: true, although  ts-loader outputs its declaration files into your output folder, building up an absolutely path tree to your project folder _within_ your project's output folder.

I could around it by making two passes with separate tsconfigs, the first without declarations so I could get my inline templates, and second with declarations outputting to a different folder. Then I grab the declarations from that folder and bring them in to my output folder.

If it's not one thing it's another. :)

**Comment by ghetolay** [comment]
@nikolasleblanc Thank you !

I couldn't find why I was unable to get it working while the [angular 2 webpack starter](https://github.com/AngularClass/angular2-webpack-starter) project got it working fine.

So it's just a duplicate of #19, closing it.
Also thks for your workaround but it seems way too complicated for the benefits of `awesome-typescript-loader`, I'll just stick with `ts-loader` until it's resolved.
