### ISSUE TITLE
Bug: space after templateUrl and : causes No ResourceLoader error

### ISSUE THREAD

**Issue by MarkPieszak** [TheLarkInn/angular2-template-loader#57]
Example :
```
templateUrl : './sometemplate.component.html' <- not good
templateUrl: './sometemplate.component.html' <- good
```

I'll take a look at the project this week to see what the regex is doing to cause it.

**Comment by tuxado** [comment]
hi, 

You can close this topic the problem was solved i have update the angular2-template-loader package version to ^0.6.2 because the error come by using the version 0.4.0 on the universal-starter you should update the universal-starter package file only

tkx
