### ISSUE TITLE
option to prefix the require url (for example with !to-string-loader!raw-loader!)

### ISSUE THREAD

**Issue by mo22** [TheLarkInn/angular2-template-loader#59]
Usually the webpack.config.js already contains some rules for loading .html or .css files. angular2-template-loader requires a webpack config that either returns .html/.css urls as string or as absolute url.
It would be nice to be able to keep the webpack config as it is and pass a prefix string to angular2-template-loader, for example "!to-string-loader!raw-loader!" so that ./test.html becomes require('!to-string-loader!raw-loader!./test.html')

**Comment by TheLarkInn** [comment]
Hey @mo22 Thanks for the question. What you should do is add an additional loader that uses our new `issuer:` feature. This allows you to filter which loader gets processed based on the file that requested it. 

Therefore, if a ts file imports a .css/.html file, you can specially define and chain loaders.

Heres some relevant documentation. https://webpack.js.org/configuration/module/#rule

You may experiment with `issuer: /\.component\.ts/` or something similar.
