### ISSUE TITLE
Is your documentation right?

### ISSUE THREAD

**Issue by dland512** [TheLarkInn/angular2-template-loader#60]
I'm having trouble understanding your documentation. The code snippet given is

```
@Component({
  selector: 'awesome-button',
  template: require('./button.template.html'),
  styles: [require('./button.style.css')]
})
export class AwesomeButtonComponent { }
```
But then right below that it says

> The angular2-template-loader searches for templateUrl and styleUrls declarations inside of the Angular 2 Component metadata and replaces the paths with the corresponding require statement

So why does the example use `template` and `styles`? What am I not getting here?

**Comment by dland512** [comment]
I don't think it's quite right yet. You're "before" example still uses the `template` and `styles` properties when it should be using `templateUrl` and `styleUrls`.

**Comment by GiuseppePiscopo** [comment]
Was going to open a PR just for this. It seems wrong to me as well, but of course ... I might be wrong.

The way I see it, readme should look something like:

***

#### Before loader (your original code)
```js
@Component({
  selector: 'awesome-button',
  templateUrl: 'button.template.html',
  styleUrls: ['button.style.css']
})
export class AwesomeButtonComponent { }
```

#### After loader (before it is bundled into your webpack'd application)
```js
@Component({
  selector: 'awesome-button',
  template: require('./button.template.html'),
  styles: [require('./button.style.css')]
})
export class AwesomeButtonComponent { }
```

**Comment by GiuseppePiscopo** [comment]
Looking at current specs, my understanding seems to be ok:

* this is the [sample code](https://github.com/TheLarkInn/angular2-template-loader/blob/c2dc8874c29266dbccfd3339b102f490b54b0c1c/test/fixtures/sample_angular_component_file_string_simple.js#L6)
* this is the [expected output](https://github.com/TheLarkInn/angular2-template-loader/blob/c2dc8874c29266dbccfd3339b102f490b54b0c1c/test/loader.spec.js#L17)

**Comment by dland512** [comment]
@GiuseppePiscopo, that's in line with my understanding as well. Hopefully your PR will get merged soon.
