### ISSUE TITLE
Template is loaded as a es module object instead of a string in modern Webpack

### ISSUE THREAD

**Issue by samal-rasmussen** [TheLarkInn/angular2-template-loader#89]
I just updated Webpack and suddenly no template would load properly. By setting a breakpoint just after a component is loaded I could see that the template was loaded as a es module object and not as a html template string any more.

Setting esModule to false in the html-loader settings fixed this.
https://webpack.js.org/loaders/html-loader/#esmodule

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.html$/i,
        loader: "html-loader",
        options: {
          esModule: false,
        },
      },
    ],
  },
};
```

**Comment by charliech17** [comment]
@samal-rasmussen try to use asset loader 

`{
                test: /\.html$/,
                type: 'asset/source',
                generator: {
                    filename: 'assets/[name]-[contenthash].[ext]',
                },
            },`
