### ISSUE TITLE
Add documentation to mention needing ambient require typing.

### ISSUE THREAD

**Issue by TheLarkInn** [TheLarkInn/angular2-template-loader#9]
Since the template loader replaces strings with `requires()` if users are using typescript `module: es2015`, they will get typing errors for require. We should probably mention that an ambient typing is needed, if one doesn't already exist in README instructions.

**Comment by DevVersion** [comment]
Thanks for the hint, I was running into that issue as well :) 

I currently use the `dt~node` typings, but it feels wrong to have those for an application, which runs inside of a browser.

Any other suggestions to solve that? (without manually creating those)

**Comment by TheLarkInn** [comment]
One solution would be calling a chained loader from withinside this loader I would need to dig into some other loaders like file-loader and see if it's possible.

**Comment by DevVersion** [comment]
Cool thanks for your efforts. Keep us updated :)

**Comment by TheLarkInn** [comment]
Sure :) and a pr for this documentation issue is ALWAYS welcome! 🙏🙏

**Comment by DevVersion** [comment]
Sure, I had some time to help you out :smile: . Here is the related PR #16
